// Full menu seed for Amrutham by Padma Catering
// Run from server/ folder: node prisma/seed-menu.js
// This script is NON-DESTRUCTIVE - it upserts categories and replaces items per category

require('dotenv').config()
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

const MENU = [
  { name: 'Welcome Drinks', order: 1, items: ['Pine Apple Juice','Grape Juice','Water Melon Juice','Muskmelon Juice','Banana Juice','Papaya Juice','Sugar Cane Juice','Mango Juice','Sapota Juice','Seethaphal Juice','Orange Juice','Pine Apple Milk Shake','Orange Milk Shake','Strawberry Milk Shake','Litchi Milk Shake','Mango Milk Shake','Vanilla Milk Shake','Banana Milk Shake','Chocolate Milk Shake','Seethaphal Milk Shake','Sapotha Milkshake','Butter Scotch Milk Shake','Oreo Milk Shake','Kitkat Milk Shake','Coffee Milk Shake','Caramel Milk Shake','Choco Peanut Milk Shake','Fruit Punch Milk Shake','Kesar Badam Milk Shake','Blue Sea','Raspberry Mojito','Virgin Mojito','Lime & Mint Mojito','Green Apple Mojito','Black Currant Mojito','Pink Lady','Mint Green','Peach Melba','Strawberry Surprise','Kiwi Kiss','Passion Punch','Lassi','Dry Fruit Lassi','Masala Chaas','Butter Milk','Rose Milk','Hot Rose Milk','Badam Milk','Hot Badam Milk','Dry Fruit Milk','Aam Panna','Coconut Water','Jaljeera','Nimbu Pani'] },
  { name: 'Salads', order: 2, items: ['Green Salad','Cucumber Salad','Sprouts Salad','Russian Salad','Pulses Salad','Macroni Salad','Aloo Channa Salad','Rajma Salad','Corn Cheese Salad','Pickled Onion Salad','Coleslaw Salad','Butter Tossed Paneer','Mushroom Salad','Mediterian Salad','Fresh Garden Salad','Chickpea Salad','Peanut Cucumber Tomato','Ceaser Salad'] },
  { name: 'Soups', order: 3, items: ['Tomato Soup','Clear Soup','Sweet Corn Soup','Hot & Sour Soup','Mushroom Soup','Manchow Soup','Veg Noodle Soup','Thai Clear Soup','Thai Coconut Soup','Cream of Tomato','Cream of Brocolli'] },
  { name: 'Starters', order: 4, items: ['Veg Manchuria','Schezwan Manchuria','Dice Cut Manchuria','Paneer Manchuria','Paneer Lemon Zest Manchuria','Potato Manchuria','Baby Corn Manchuria','Gobi Manchuria','Mushroom Manchuria','Tangy Chilli Stick','Paneer Sticks','Crispy Baby Corn Stick','Chilli Mushroom Stick','Veg Sticks','Thai Stick with White Sauce','Hot Garlic Sauce Sticks','Onion Rings','Banana Bytes','Capsicum Rings','Pudina Byte','Crispy Baby Corn Byte','Corn Cheese Byte','Veg Bytes','French Fries Salted','French Fries Piri Piri','Potato Wedges','Garlic Potato Bytes','Cheese Bytes','Veg Nuggets','Smilies','Veg Cutlet','Aloo Tikki','Veg Rolls','Noodle Roll','Sweet Corn Rolls','Mushroom Garlic Roll','Paneer Roll','Palak Cheese Roll','Corn Cheese Roll','Shangai Roll','Veg Kathi Roll','Paneer Kathi Roll','Mushroom Kathi Roll','Veg Greens Kathi Roll','Bread Roll','Chilly Paneer','Chilli Mushroom','Chilli Baby Corn','Chilly Potato Finger','Chilly Gobi','Tread Paneer','Paneer Tikka','Paneer Hariyali Tikka','Hara Bara Tikka','Gobi 65','Paneer 65','Aloo 65','Gold Coin','Veg Wontons','Paneer Wontons','Corn Samosa','Cheese Samosa','Onion Samosa','Dry Fruit Samosa','Veg Momo','Fried Momo','Tawa Sizzler','Tangy Paneer','Veg Dumpling','Veg Panipoori Shots','Cheesey Panipoori Shots','Cajun Potato','Peri Peri Potato','Mexican Tostada','Malai Paneer Kabab','Gobi Kabab','Soya Kabab','Corn Kabab','Tandoori Aloo','Mushroom Kabab','Veg Seekh Kabab','Malai Vegetable','Achari Paneer','Pineapple Tikka','Malai Brocolli','Malai Chaap Kebab','Malai Galouti Kebab','Red Pasta','White Pasta','Garlic Bread','Pizza','Bruschetta','Mushroom Risotto','Stuffed Ravioli','Spaghetti','Veg Burritos','Tacos with Salsa','Nachos','Burrito','Quesadilla','Chilaquiles','Tamales','Enchiladas'] },
  { name: 'Indian Breads', order: 5, items: ['Roti','Palak Roti','Carrot Roti','Masala Roti','Jeera Roti','Butter Roti','Rumali Roti','Palak Rumali Roti','Chapathi','Butter Naan','Garlic Butter Naan','Dry Fruit Butter Naan','Kulcha','Stuffed Kulcha','Paneer Kulcha','Cheese Kulcha','Parantha','Stuffed Parantha','Paneer Parantha','Malabar Parotha','Coin Malabar Parotha','Bhatura','Poori','Meetha Poori','Meetha Roti','Flavoured Poori','Besan Ki Poori','Biscuit Roti','Paneer Kottu Parotha','Mix Veg Kothu Parotha'] },
  { name: 'Flavoured Rice', order: 6, items: ['Pulihora','Lemon Rice','Mamidikay Pulihora','Veg Biryani','Bagara Rice','Veg Dum Biryani','Sweet Corn Biryani','Baby Corn Biryani','Soya Biryani','Tiranga Biryani','Kaju Peas Pulao','Peas Pulao','Paneer Pulao','Kashmiri Pulav','Mutter Methi Pulao','Tavva Pulao','Chinese Fried Rice','English Vegetable Fried Rice','Schezwan Fried Rice','Gobi Rice','Tomato Rice','Pudina Rice','Jeera Rice','Steamed Rice','Plain Rice','Saffron Rice','Basmati Rice','Panasakay Biryani','Pudina Corn Rice','Palak Rice','Raagi Sankati','Ragi Muddha','Avakay Biryani','Karvepaku Rice','Live Pickle Rice','Gongura Pandumirchi Rice','Avakai Mudapappu Annam','Mushroom Biryani','Mexican Rice','Seven Jewel Rice','Vulavacharu Biryani','Mango Pulihora','Coconut Rice','Hot Pongal','Dal Khichidi','Bisibela Bath','Kothimeera Rice','Vangi Bath','Gongura Rice','Daddojjanam','Spl Curd Rice'] },
  { name: 'Raithas', order: 7, items: ['Plain Beaten Curd','Onion Raitha','Mix Veg Raitha','Keera Raitha','Anar Ka Raitha','Keera Tomato Raitha','Pineapple Raitha','Tomato Raitha','Boondi Raitha','Jeera Raitha','Potlakay Raitha','Masala Raitha'] },
  { name: 'North Indian', order: 8, items: ['Paneer Kadai','Paneer Mutter','Shahi Paneer','Kaju Paneer','Paneer Butter Masala','Malai Methi Paneer','Paneer Meethi Chaman','Paneer Tikka Masala',
