// Full menu seed — Amrutham by Padma Catering
// Run: cd server && node prisma/seed-menu.js
require('dotenv').config()
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

const MENU = [
  { name: 'Welcome Drinks', order: 1, items: ['Pine Apple Juice','Grape Juice','Water Melon Juice','Muskmelon Juice','Banana Juice','Papaya Juice','Sugar Cane Juice','Mango Juice','Sapota Juice','Seethaphal Juice','Orange Juice','Pine Apple Milk Shake','Orange Milk Shake','Strawberry Milk Shake','Litchi Milk Shake','Mango Milk Shake','Vanilla Milk Shake','Banana Milk Shake','Chocolate Milk Shake','Seethaphal Milk Shake','Sapotha Milkshake','Butter Scotch Milk Shake','Oreo Milk Shake','Kitkat Milk Shake','Coffee Milk Shake','Caramel Milk Shake','Choco Peanut Milk Shake','Fruit Punch Milk Shake','Kesar Badam Milk Shake','Blue Sea','Raspberry Mojito','Virgin Mojito','Lime Mint Mojito','Green Apple Mojito','Black Currant Mojito','Pink Lady','Mint Green','Peach Melba','Strawberry Surprise','Kiwi Kiss','Passion Punch','Lassi','Dry Fruit Lassi','Masala Chaas','Butter Milk','Rose Milk','Hot Rose Milk','Badam Milk','Hot Badam Milk','Dry Fruit Milk','Aam Panna','Coconut Water','Jaljeera','Nimbu Pani'] },
  { name: 'Salads', order: 2, items: ['Green Salad','Cucumber Salad','Sprouts Salad','Russian Salad','Pulses Salad','Macroni Salad','Aloo Channa Salad','Rajma Salad','Corn Cheese Salad','Pickled Onion Salad','Coleslaw Salad','Butter Tossed Paneer','Mushroom Salad','Mediterian Salad','Fresh Garden Salad','Chickpea Salad','Peanut Cucumber Tomato','Ceaser Salad'] },
  { name: 'Soups', order: 3, items: ['Tomato Soup','Clear Soup','Sweet Corn Soup','Hot Sour Soup','Mushroom Soup','Manchow Soup','Veg Noodle Soup','Thai Clear Soup','Thai Coconut Soup','Cream of Tomato','Cream of Brocolli'] },
  { name: 'Starters', order: 4, items: ['Veg Manchuria','Schezwan Manchuria','Dice Cut Manchuria','Paneer Manchuria','Paneer Lemon Zest Manchuria','Potato Manchuria','Baby Corn Manchuria','Gobi Manchuria','Mushroom Manchuria','Tangy Chilli Stick','Paneer Sticks','Crispy Baby Corn Stick','Chilli Mushroom Stick','Veg Sticks','Thai Stick with White Sauce','Hot Garlic Sauce Sticks','Onion Rings','Banana Bytes','Capsicum Rings','Pudina Byte','Crispy Baby Corn Byte','Corn Cheese Byte','Veg Bytes','French Fries Salted','French Fries Piri Piri','Potato Wedges','Garlic Potato Bytes','Cheese Bytes','Veg Nuggets','Smilies','Veg Cutlet','Aloo Tikki','Veg Rolls','Noodle Roll','Sweet Corn Rolls','Mushroom Garlic Roll','Paneer Roll','Palak Cheese Roll','Corn Cheese Roll','Shangai Roll','Veg Kathi Roll','Paneer Kathi Roll','Mushroom Kathi Roll','Veg Greens Kathi Roll','Bread Roll','Chilly Paneer','Chilli Mushroom','Chilli Baby Corn','Chilly Potato Finger','Chilly Gobi','Tread Paneer','Paneer Tikka','Paneer Hariyali Tikka','Hara Bara Tikka','Gobi 65','Paneer 65','Aloo 65 Starter','Gold Coin','Veg Wontons','Paneer Wontons','Corn Samosa','Cheese Samosa','Onion Samosa','Dry Fruit Samosa','Veg Momo','Fried Momo','Tawa Sizzler','Tangy Paneer','Veg Dumpling','Veg Panipoori Shots','Cheesey Panipoori Shots','Cajun Potato','Peri Peri Potato','Mexican Tostada','Malai Paneer Kabab','Gobi Kabab','Soya Kabab','Corn Kabab','Tandoori Aloo','Mushroom Kabab','Veg Seekh Kabab','Malai Vegetable','Achari Paneer','Pineapple Tikka','Malai Brocolli','Malai Chaap Kebab','Malai Galouti Kebab','Red Pasta','White Pasta','Garlic Bread','Pizza Counter','Bruschetta','Mushroom Risotto','Stuffed Ravioli','Spaghetti','Veg Burritos','Tacos with Salsa','Nachos','Burrito','Quesadilla','Chilaquiles','Tamales','Enchiladas'] },
  { name: 'Indian Breads', order: 5, items: ['Roti','Palak Roti','Carrot Roti','Masala Roti','Jeera Roti','Butter Roti','Rumali Roti','Palak Rumali Roti','Chapathi','Butter Naan','Garlic Butter Naan','Dry Fruit Butter Naan','Kulcha','Stuffed Kulcha','Paneer Kulcha','Cheese Kulcha','Parantha','Stuffed Parantha','Paneer Parantha','Malabar Parotha','Coin Malabar Parotha','Bhatura','Poori','Meetha Poori','Meetha Roti','Flavoured Poori','Besan Ki Poori','Biscuit Roti','Paneer Kottu Parotha','Mix Veg Kothu Parotha'] },
  { name: 'Flavoured Rice', order: 6, items: ['Pulihora','Lemon Rice','Mamidikay Pulihora','Veg Biryani','Bagara Rice','Veg Dum Biryani','Sweet Corn Biryani','Baby Corn Biryani','Soya Biryani','Tiranga Biryani','Kaju Peas Pulao','Peas Pulao','Paneer Pulao','Kashmiri Pulav','Mutter Methi Pulao','Tavva Pulao','Chinese Fried Rice','English Vegetable Fried Rice','Schezwan Fried Rice','Gobi Rice','Tomato Rice','Pudina Rice','Jeera Rice','Plain Rice','Saffron Rice','Basmati Rice','Panasakay Biryani','Pudina Corn Rice','Palak Rice','Raagi Sankati','Ragi Muddha','Avakay Biryani','Karvepaku Rice','Live Pickle Rice','Gongura Pandumirchi Rice','Avakai Mudapappu Annam','Mushroom Biryani','Mexican Rice','Seven Jewel Rice','Vulavacharu Biryani','Mango Pulihora','Coconut Rice','Hot Pongal','Dal Khichidi','Bisibela Bath','Kothimeera Rice','Vangi Bath','Gongura Rice','Daddojjanam','Spl Curd Rice'] },
  { name: 'Raithas', order: 7, items: ['Plain Beaten Curd','Onion Raitha','Mix Veg Raitha','Keera Raitha','Anar Ka Raitha','Keera Tomato Raitha','Pineapple Raitha','Tomato Raitha','Boondi Raitha','Jeera Raitha','Potlakay Raitha','Masala Raitha'] },
  { name: 'North Indian', order: 8, items: ['Paneer Kadai','Paneer Mutter','Shahi Paneer','Kaju Paneer','Paneer Butter Masala','Malai Methi Paneer','Paneer Meethi Chaman','Paneer Tikka Masala','Chole Paneer','Soya Mutter','Mutter Baby Corn','Mutter Gobi','Palak Paneer','Paneer Koftha','Paneer Baby Corn','Paneer Burji','Paneer Mirchi Masala','Tawa Paneer','Mushroom Masala','Kadai Mushroom','Tawa Mushroom','Mushroom Cheese Delight','Mushroom Capsicum','Mushroom Mutter','Mix Vegetables Kadai','Navaratan Kurma','Aloo Capsicum','Aloo Gobi','Aloo Mutter','Dhum Aloo','Bagara Baigan','Tomato Bagara','Chole Masala','Capsicum Masala','Kaju Malai Mutter','Veg Koftha Curry','Cheese Kofta','Palak Koftha','Mirchi Ka Salan','Aloo Palak','Tawa Sabji','Dry Fruit Vegetables','Veg Dopiaza','Veg Jaipuri','Veg Jalfrize','Rajma Curry','Achari Sabzi','Kaju Makhana','Bendi Masala'] },
  { name: 'Veg Curries', order: 9, items: ['Guthi Vankay Curry','Methi Vankay Curry','Aloo Tomato Curry','Aloo Gobi Curry','Aloo Kurma','Mix Vegetable','Malai Guti Vankay Curry','Vankay Tomato','Drumstick Tomato','Drumstick Cashew','Tomato Curry','Mamidikay Jeedipapu','Jeedigundu Velluli Curry','Vadiyala Pulsu','Pesara Punugula Curry','Guthi Dondakay Curry','Bendakay Pulusu','Kanda Pulusu Curry','Pallu Birakaya Curry','Pallu Potlakaya Curry','Gobi Curry','Chikudikay Curry','Natu Chikudikay Curry','Kanda Bachali','Mushroom Curry','Gongura Meal Mekhar','Gongura Senagapappu','Panasakay Jeedipapu Curry','Sorakay Pallu Curry','Beerakay Senagapappu Curry','Vankay Senagapappu Curry','Vankay Batani Curry','Artikay Curry','Phool Makani Gongura','Macroni Gongura Curry','Jeddigundlu Tomato Curry','Gumadikay Curry','Mamidikay Vankay Curry','Kalagalupu Curry','Sema Dumpa Pulusu','Gongura Keema Curry','Chikudikay Aloo Curry','Mango Small Onion Cashew Curry'] },
  { name: 'Veg Fries', order: 10, items: ['Aloo 65','Gobi 65','Bendi 65','Dondakay 65','Totakkura 65','Cabbage 65','Kanda Pusa','Aloo Pusa','Veg Kheema','Banana Chips','Navaratan Fry','Dondakay Kobbari','Cabbage Carrot Beans Poriyal','Artikaya Pesarapappu','Totakkura Liver Fry','Aloo Boiled Puttu','Dondakay Boondi Nut Fry','Bendakay Boondi Nut Fry','Mix Veg 65','Chikudukay Fry','Vankay Methi Karam','Stuffed Vankay','Avial','Capsicum Fry','Baby Corn Fry','Panasa Pottu','Gutivankay Senagakaram','Kakarakay Fry','Carrot Boiled Fry','Potlakay Fry','Vulavacharu Mushroom Fry','Mushroom Liver Fry','Aloo Methi Fry','Aloo Gobi Fry','Aloo Capsicum Fry','Chammagadha Fry','Capsicum 65','Potlakay 65'] },
  { name: 'Dalls', order: 11, items: ['Tomato Pappu','Anapakay Pappu','Chukkakura Pappu','Bachalikura Pappu','Gongoora Pappu','Mamidi Kaya Pappu','Mudda Pappu','Beerakaya Pappu','Tomato Pesara Pappu','Chinthakaya Pappu','Dosakaya Pappu','Nimmakaya Pappu','Thota Kura Pappu','Rajma Dal','Palak Dal','Dal Fry','Dal Makhani'] },
  { name: 'Sambar and Liquids', order: 12, items: ['Drumstick Sambar','Sambar','Madras Sambar','Pappucharu','Veg Dhalcha','Mukkala Pulusu','Munakkaya Charu','Tomato Charu','Ulawa Charu','Bendakaya Charu','Tomato Rasam','Miryala Rasam','Beetroot Rasam','Udipi Rasam','Pachi Pulusu','Majjiga Pulusu','Kadi Pakoda','Ulavacharu with Cream'] },
  { name: 'Pickles and Podis', order: 13, items: ['Dosa Avakaya','Gobi Avakaya','Donda Avakaya','Mango Pickle','Lime Pickle','Mixed Veg Pickle','Gongoora Pickle','Gongoora Chutney','Tomato Pickle','Tomato Chutney','Cabbage Chutney','Carrot Chutney','Allam Chutney','Beerakaya Chutney','Dosakaya Chutney','Vankaya Dosakaya Chutney','Pudina Chutney','Pudina Coconut','Kobbari Pachadi','Chintakay Pickle','Amla Pickle','Red Chilly Pickle','Mango Turumu','Kothimeera Pickle','Kobbari Mamidi','Kandi Pachadi','Allam Pachadi','Carrot Pickle','Roti Pachadi','Dondakay Mukkala','Kandi Podi','Karam Podi','Ildy Karam','Nalla Karam','Putnala Podi','Karvepaku Podi','Velluli Karam'] },
  { name: 'Accompaniments', order: 14, items: ['Plain Papad Big','Masala Papad','Vadiyalu','Curd Chillies','Frymus','Curd','Rajula Perugu','Pot Curd','Mouth Freshener'] },
  { name: 'Sweets', order: 15, items: ['Gulab Jamun','Chum Chum','Kala Jamun','Rasgulla','Boorellu','Bobbatllu','Kakinada Kaja','Kaju Katli','Putharekkulu','Jilebi','Jangeri','Mysore Pak','Milk Mysore Pak','Motichoor Ladoo','Bandhar Ladoo','Soan Papidi','Arisellu','Badhusha','Paramanam','Chekkara Pongali','Dood Peda','Double Ka Meetha','Triple Pudding','Paneer Jilebi','Badam Katli','Kaju Pan','Coconut Rabidi','Rabidi','Tiranga Burfi','Dry Fruit Sandwich','Badam Roll','Chocolate Roll','Kaju Roll','Coconut Burfi','Apple Sweet','Custard Apple Sweet','Chandra Kala','Kaja','Malai Poori','Malai Roll','Malai Chum Chum','Anjeer Coin','Dry Fruit Putharekulu','Gajjar Ka Halwa','Rasmalai','Boondi Ladoo','Kova Puri','Semiya Payasam','Kaddu Ka Halwa','Kadhu Ka Kheer','Gajjar Ka Kheer','Qurbani Ka Meetha','Basundi','Apricot Pudding','Tawa Sweet','Honey Malai','Chocolate Florentine','Chocolate Malai Boat','Coconut Malai Rabdi','Kiwi Rabdi','Red Velvet Temptation','Matka Rabdi Basanthi','Rabdi Chum Chum','Kaju Delight','Dry Fruit Halwa Mini','Dry Fruit Laddu Mini','Mini Kaja','Mini Motichoor Ladoo','Kova Bobbattu','Kaju Gajak','Pista Gajak','Kesar Gajak','White Choco Laddu','Rose Gulkandh Ladoo','Dry Fruit Dates Delight','Sunnundalu','Junnu','Badam Junnu','Icecream Burfi','Jaggery Rasgulla','Pichigullu','Palathalikelu'] },
  { name: 'Ice Creams', order: 16, items: ['Vanilla Ice Cream','Strawberry Ice Cream','Orange Ice Cream','Pineapple Ice Cream','Mango Ice Cream','Chocolate Ice Cream','Seethapal Ice Cream','Choco Chips Ice Cream','Pista Ice Cream','Butter Scotch Ice Cream','Kulfi Malai','Honeymoon Delite','Honey Almond','Dry Fruit Temptation','Mello Jello','Fruit Ninja','Black Current Ice Cream','Anjeer Badam Ice Cream','Caramel Nuts','Belgium Dark Chocolate','Choco Fudge','Cassata','Single Sundaes','Double Sundaes','Mixed Fruit Sundaes','Matka Kulfi','Dry Fruit Kulfi'] },
  { name: 'Breakfast', order: 17, items: ['Idly','Carrot Idly','Mix Veg Idly','Ragi Idly','Aviri Kudumu','Potupappu Idly','Rava Idly','Thatte Idly','Vada','Cocktail Vada','Dahi Vada','Sabudana Vada','Plain Dosa','Onion Dosa','Masala Dosa','Upma Dosa','Karam Dosa','Pizza Dosa','Paneer Dosa','Mushroom Dosa','Cashew Dosa','Sponge Dosa','Pesaratu','Utappam','Ragi Dosa','Beetroot Dosa','Set Dosa','Rava Dosa','Millet Dosa','Spl Cheese Dosas','Poori','Chole Batura','Mysore Bajji','Punugulu','Gunta Pongadallu','Vegetable Upma','Yerra Rava Upma','Semiya Upma','Tomato Bath','Poha','Dhokla','Besan Chilla','Sabudana Kichidi','Kara Bath','Parotha','Mini Parotha','Kichidi','Butter Phulka','Waffles','Pancakes','Oat Meal','Fruit Salad'] },
  { name: 'Millets', order: 18, items: ['Multi Millet Idly','Millet Dosa','Korrala Kichidi','Jowar Upma','Korra Pongal','Korra Payasam','Ragi Roti','Ragi Dosa Millet','Millet Pancakes','Mini Millet Uttapam','Millet Vadalu','Millet Lemon Rice'] },
  { name: 'Chutneys', order: 19, items: ['Coconut Chutney','Peanut Chutney','Allam Chutney Breakfast','Tomato Chutney Breakfast','Pudina Chutney','Corriander Chutney','Corriander Coconut Chutney','Onion Chutney','Garlic Chutney','Kollar Chutney','Morringa Chutney','Red Chilli Dahi Chutney','Bombay Chutney','Idly Karam','Kandi Podi Chutney','Nalla Karam'] },
  { name: 'Beverages and Sides', order: 20, items: ['Tea','Coffee','Black Coffee','Black Tea','Green Tea','Lemon Tea','Badam Tea','Milk','Boost Horlicks','Lemon Water','Sabudana Java','Millet Java','Yogurt','Rava Kesari','Dry Fruit Kesari','Pine Apple Kesari','Apple Kesari','Semiya Kesari','Kashi Halwa','Payasam','Paravanam','Kheer','Muffins','Corn Flakes','Museli','Nuts'] },
  { name: 'Live Counters', order: 21, items: ['Aloo Tikki Counter','Laccha Tikki Counter','Coconut Tikki Counter','Dryfruit Tikki Counter','Beetroot Tikki Counter','Vegetable Tikki Counter','Corn Tikki Counter','Chole Tikki Counter','Ragda Tikki Counter','Mutter Tikki Counter','Veg Cutlet Counter','Khowa Paneer Cutlet Counter','Banana Cutlet Counter','Mutter Cutlet Counter','Agra Bhalla Counter','Sweet Corn Paneer Cutlet Counter','Butter Pav Bhaji','Cheese Pav Bhaji','Italian Pav Bhaji','Mexican Pav Bhaji','Thai Pav Bhaji','Garlic Pav Bhaji','Paneer BBQ','Malai Paneer BBQ','Vegetable BBQ','Fruit BBQ','Soya Chaap BBQ','Malai Chaap BBQ','Assorted BBQ','Normal Bhel','Papdi Bhel','Ghee Garlic Bhel','Mixture Bhel','Navratan Bhel','Chinese Bhel','Panch Ratan Bhel','Mexican Bhel','Andhra Dahi Wada','Raj Bhog Dahi Wada','Malai Dahi Wada','Moong Dal Dahi Wada','Pineapple Dahi Wada','Strawberry Dahi Wada','Mini Dahi Wada','Assorted Dahi Wada','Aloo Tikki Chaat','Mutter Chaat','Samosa Chaat','Paneer Kangna Chaat','Baby Corn Kangna Chaat','Aloo Basket Chaat','Delhi Tava Mix Chaat','Tava Sweet Corn Chaat','Vada Pav Chaat','Papidi Chaat','Delhi Dahi Gujiya Chaat','Bhala Papdi Chaat','Dahi Kachodi Chaat','Dahi Samosa Chaat','Delhi Raj Kachodi Chaat','Masala Paneer Tikka Chaat','Paneer Lifafa Chaat','Imli Pani Poori','Tomato Pani Poori','Garlic Pani Poori','Meetha Pani Poori','Hing Pani Poori','Chocolate Pani Poori','Delhi Rava Pani Puri','Bombay Moong Dal Pani Puri','Kolkata Pani Puri'] },
]

async function main() {
  console.log('Seeding full menu into database...')
  let totalItems = 0

  for (const cat of MENU) {
    let category = await prisma.menuCategory.findFirst({ where: { name: cat.name } })
    if (category) {
      await prisma.menuCategory.update({ where: { id: category.id }, data: { sortOrder: cat.order } })
    } else {
      category = await prisma.menuCategory.create({
        data: { name: cat.name, sortOrder: cat.order, active: true },
      })
    }

    // Get existing item names to avoid duplicates
    const existing = await prisma.menuItem.findMany({
      where: { categoryId: category.id },
      select: { name: true },
    })
    const existingNames = new Set(existing.map(i => i.name))
    const newItems = cat.items.filter(name => !existingNames.has(name))

    let count = 0
    if (newItems.length > 0) {
      const result = await prisma.menuItem.createMany({
        data: newItems.map(name => ({
          name,
          categoryId: category.id,
          style: 'ANDHRA',
          type: 'VEG',
          price: 0,
          active: true,
        })),
      })
      count = result.count
    }
    console.log(`  ${category.name}: +${count} new items (${existingNames.size} existing)`)
    totalItems += count
  }

  console.log(`\nDone! ${MENU.length} categories, ${totalItems} items seeded.`)
}

main()
  .catch(err => { console.error('Seed error:', err.message); process.exit(1) })
  .finally(() => prisma.$disconnect())
